// Catálogo de códigos de error, compartido por apps/api y apps/web (docs/04-manejo-de-errores.md).
// Un código se agrega junto con la funcionalidad que lo lanza, no antes.
module.exports = {
  ERROR_INTERNO: 'ERROR_INTERNO',
  RUTA_NO_ENCONTRADA: 'RUTA_NO_ENCONTRADA',
  DEMASIADAS_SOLICITUDES: 'DEMASIADAS_SOLICITUDES',
  JSON_INVALIDO: 'JSON_INVALIDO',
  VALIDACION_ENTRADA: 'VALIDACION_ENTRADA',
  CONSENTIMIENTO_REQUERIDO: 'CONSENTIMIENTO_REQUERIDO',
  AUTH_CORREO_YA_REGISTRADO: 'AUTH_CORREO_YA_REGISTRADO',
  AUTH_CREDENCIALES_INVALIDAS: 'AUTH_CREDENCIALES_INVALIDAS',
  AUTH_TOKEN_EXPIRADO: 'AUTH_TOKEN_EXPIRADO',
  AUTH_TOKEN_INVALIDO: 'AUTH_TOKEN_INVALIDO',
  AUTH_CUENTA_BLOQUEADA: 'AUTH_CUENTA_BLOQUEADA',
  AUTH_EMAIL_NO_VERIFICADO: 'AUTH_EMAIL_NO_VERIFICADO',
  NO_AUTORIZADO: 'NO_AUTORIZADO',
};
